#!/bin/sh

# SPDX-FileCopyrightText: 2019 Hans Ulrich Niedermann <hun@n-dimensional.de>
#
# SPDX-License-Identifier: CC0-1.0

# failing sounding A minor-whatever arpeggio
beep -f 880 -l 200  -n -f 659  -n -f 523  -n -f 370 -l 400
